server.port=9191
spring.application.name=KafkaMessaging
spring.kafka.bootstrap-servers= d-kafka-broker3.athexsrv.gr:9092
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.springframework.kafka.support.serializer.JsonSerializer